# Strings used in CalCorrupt

'''Distributed under the GNU GPL-3.0-or-later.'''

VERSION = "1.0.2"
TITLE = "CalCorrupt "+VERSION
HEADER = "Welcome to CalCorrupt "+VERSION+"."
OPEN_DIALOGUE = "Open. The file will be edited directly, so be careful and make backups!"
NO_FILE_OPENED = "No file opened."
FILE_MENU = "&File"
HELP_MENU = "&Help"
FILE_OPEN = "&Open"
FILE_QUIT = "&Quit"
HELP_HOWTO = "How To"
HELP_ABOUT = "About"

CORRUPT_EVERY = "Corrupt every"
TH = "-th byte."
FILE_CORRUPTED = "File corrupted successfully!"
FILE_NOT_CORRUPTED = "File not corrupted."
CORRUPTION_SETTINGS = "Corruption Settings:"
CORRUPTION_OPTIONS = "Corruption Options:"
FILE_INFO = "File information:"
FILE_TYPE = "Type:"
FILE_LENGTH = "Length:"
CORRUPT_EVERY_N = "Corrupt every n bytes: "
START_BYTE = "Start byte: "
END_BYTE = "End byte:"
OPTIONAL = "-1 for all"
CHANCE = "Chance:"
PERCENT = "%"
INCREMENT = "&Increment by"
MULTIPLY = "&Multiply by"
POWER = "&Power (byte ^ v)"
EXPONENT = "E&xponent (v ^ byte)"
LOG = "&Log, base"
INVERT = "In&vert (v - byte)"
BITSHIFT = "Bi&tshift right by"
BYTESHIFT = "B&yteshift right by"
RANDOMIZE = "&Randomize byte"
CORRUPT_BUTTON = "Corrupt file!"
CORRUPTIONS_STACK = "Corruptions stack?"
MIN_FUZZ = "Min fuzz:"
MAX_FUZZ = "Max fuzz:"
CORRUPTION_VALUE = "Value (v):"

ABOUT_TITLE = "About CalCorrupt "+VERSION+"."
ABOUT_TEXT = "CalCorrupt "+VERSION+", an open-source file corrupter.\nLiscenced under the GNU GPL-3.0-or-later."

PY_FILE_ERROR = ".py files disallowed!"
READ_FILE_ERROR = "FILE READ ERROR!"
NOFILE_ERROR = "ERROR: You must open a file first!"
INVALID_CORRUPTION_ERROR = "ERROR: Invalid corruption option. Contact the developer!"
BYTE_RANGE_ERROR = "ERROR: The end byte cannot be set to a lower value than the starting byte!"
FUZZ_RANGE_ERROR = "ERROR: The max fuzz cannot be set to a lower value than the min fuzz!"

CORRUPTION_VALUE_ERROR_TEXT = "You must set a valid corruption value!"
EVERY_N_ERROR_TEXT = "You must specify the interval on which bytes are corrupted! (Corrupt every n bytes)"
FILE_ERROR_TEXT = "You must first open a file!"
START_BYTE_ERROR_TEXT = "Enter a valid start byte!"
END_BYTE_ERROR_TEXT = "Enter a valid end byte or leave blank!"
CORRUPTION_CHANCE_ERROR_TEXT = "Enter a valid corruption chance!"
FILE_READ_ERROR = "ERROR: File could not be read!"

TH_TOOLTIP = "<html><head/><body><p>Setting to 1 will corrupt every byte.</p><p>Setting to 2 will corrupt every second byte, etc.</p></body></html>"
START_BYTE_TOOLTIP = "<html><head/><body><p>Byte to start corruption at, inclusive.</p></body></html>"
END_BYTE_TOOLTIP = "<html><head/><body><p>Byte to end corruption at, inclusive.</p></body></html>"
CHANCE_TOOLTIP = "<html><head/><body><p>Chance for each byte to be corrupted.</p></body></html>"
MIN_FUZZ_TOOLTIP = "<html><head/><body><p>Minimum value that can be added randomly</p><p>to the corruption value.</p></body></html>"
MAX_FUZZ_TOOLTIP = "<html><head/><body><p>Maximum value that can be added randomly</p><p>to the corruption value.</p></body></html>"